#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

NFT_DIR="/etc/nftables.d"
NFT_FILE="$NFT_DIR/ttl64.nft"

start_service()
{
    config_load 'qmodem_ttl'
    config_get enable 'main' 'enable' '0'
    [ "$enable" = "0" ] && return
    set_if_ttl
}

set_if_ttl()
{
    config_get ttl 'main' 'ttl' '64'
    logger -t modem_ttl "Setting TTL/Hoplimit to $ttl via nftables"

    mkdir -p "$NFT_DIR"
    rm -f "$NFT_DIR"/*

    {
        echo "chain mangle_prerouting_ttl {"
        echo "  type filter hook prerouting priority 300; policy accept;"
        echo "  counter ip ttl set $ttl"
        echo "}"

        echo "chain mangle_postrouting_ttl {"
        echo "  type filter hook postrouting priority 300; policy accept;"
        echo "  counter ip ttl set $ttl"
        echo "}"

        echo "chain mangle_prerouting_hoplimit {"
        echo "  type filter hook prerouting priority 300; policy accept;"
        echo "  counter ip6 hoplimit set $ttl"
        for iface in $(ls /sys/class/net/ | grep '^wwan'); do
            echo "  iifname \"$iface\" ip6 hoplimit set $ttl"
        done
        echo "}"

        echo "chain mangle_postrouting_hoplimit {"
        echo "  type filter hook postrouting priority 300; policy accept;"
        echo "  counter ip6 hoplimit set $ttl"
        for iface in $(ls /sys/class/net/ | grep '^wwan'); do
            echo "  oifname \"$iface\" ip6 hoplimit set $ttl"
        done
        echo "}"
    } > "$NFT_FILE"

    /etc/init.d/firewall restart

    # Matikan modul NSS
    [ -d /sys/kernel/debug/ecm/ ] && /etc/init.d/qca-nss-ecm stop
    [ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
    [ -d /sys/module/fast_classifier ] && rmmod fast_classifier
}

stop_service()
{
    local kernel_version=$(uname -r)

    rm -f "$NFT_FILE"

    [ -f /etc/init.d/qca-nss-ecm ] && /etc/init.d/qca-nss-ecm start
    [ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && modprobe shortcut-fe-cm
    [ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && modprobe fast-classifier

    /etc/init.d/firewall restart
}

service_triggers()
{
    procd_add_reload_trigger "qmodem_ttl"
}

reload_service()
{
    stop
    start
}
