#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

NFT_DIR="/etc/nftables.d"
NFT_FILE="$NFT_DIR/ttl64.nft"

start_service()
{
    config_load 'qmodem_ttl'
    config_get enable 'main' 'enable' '0'
    if [ "$enable" = "0" ]; then
        return
    fi
    set_if_ttl
}

set_if_ttl()
{
    config_get ttl 'main' 'ttl'
    IPT="iptables"
    IPT6="ip6tables"
    comment="modem_ttl"

    logger -t modem_ttl "Overwrite TTL from br-lan/wwan to $ttl"

    if command -v nft >/dev/null 2>&1 && nft list tables >/dev/null 2>&1; then
        logger -t modem_ttl "Using nftables + $NFT_FILE"
        mkdir -p "$NFT_DIR"
        rm -f "$NFT_DIR"/*

        {
        cat << EOF
chain mangle_prerouting_ttl {
  type filter hook prerouting priority 300; policy accept;
  counter ip ttl set $ttl
}
chain mangle_postrouting_ttl {
  type filter hook postrouting priority 300; policy accept;
  counter ip ttl set $ttl
}
chain mangle_prerouting_hoplimit {
  type filter hook prerouting priority 300; policy accept;
  counter ip6 hoplimit set $ttl
EOF

        for iface in $(ls /sys/class/net/ | grep '^wwan'); do
            echo "  iifname \"$iface\" ip6 hoplimit set $ttl"
        done

        echo "}"

        cat << EOF
chain mangle_postrouting_hoplimit {
  type filter hook postrouting priority 300; policy accept;
  counter ip6 hoplimit set $ttl
EOF

        for iface in $(ls /sys/class/net/ | grep '^wwan'); do
            echo "  oifname \"$iface\" ip6 hoplimit set $ttl"
        done

        echo "}"
        } > "$NFT_FILE"

    else
        logger -t modem_ttl "Using iptables"
        touch /etc/firewall.d/qmodem_ttl
        echo "$IPT -t mangle -A POSTROUTING -j TTL --ttl-set $ttl -m comment --comment $comment" > /etc/firewall.d/qmodem_ttl
        echo "$IPT6 -t mangle -A POSTROUTING -j HL --hl-set $ttl -m comment --comment $comment" >> /etc/firewall.d/qmodem_ttl
        sh /etc/firewall.d/qmodem_ttl
    fi

    /etc/init.d/firewall restart

    [ -e /dev/ttyUSB3 ] && echo "AT+CFUN=1" > /dev/ttyUSB3
    [ -d /sys/kernel/debug/ecm/ ] && /etc/init.d/qca-nss-ecm stop
    [ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
    [ -d /sys/module/fast_classifier ] && rmmod fast_classifier
}

stop_service()
{
    local kernel_version=$(uname -r)

    rm -f "$NFT_FILE"
    rm -f /etc/firewall.d/qmodem_ttl

    [ -f /etc/init.d/qca-nss-ecm ] && /etc/init.d/qca-nss-ecm start
    [ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && modprobe shortcut-fe-cm
    [ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && modprobe fast-classifier
    /etc/init.d/firewall restart
}

service_triggers()
{
    procd_add_reload_trigger "qmodem_ttl"
}

reload_service()
{
    stop
    start
}
