#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

NFT_DIR="/etc/nftables.d"
NFT_FILE="$NFT_DIR/ttl64.nft"

start_service() {
    config_load 'qmodem_ttl'
    config_get enable 'main' 'enable' '0'
    [ "$enable" = "0" ] && return

    config_get ttl 'main' 'ttl' '64'
    logger -t modem_ttl "Setting TTL/Hoplimit to $ttl via nftables"

    mkdir -p "$NFT_DIR"
    rm -f "$NFT_FILE"

    cat > "$NFT_FILE" << EOF
chain mangle_prerouting_ttl {
  type filter hook prerouting priority 300; policy accept;
  counter ip ttl set $ttl
}
chain mangle_postrouting_ttl {
  type filter hook postrouting priority 300; policy accept;
  counter ip ttl set $ttl
}
chain mangle_prerouting_hoplimit {
  type filter hook prerouting priority 300; policy accept;
  counter ip6 hoplimit set $ttl
EOF

    for iface in $(ls /sys/class/net/ | grep '^wwan'); do
        echo "  iifname \"$iface\" ip6 hoplimit set $ttl" >> "$NFT_FILE"
    done

    cat >> "$NFT_FILE" << EOF
}
chain mangle_postrouting_hoplimit {
  type filter hook postrouting priority 300; policy accept;
  counter ip6 hoplimit set $ttl
EOF

    for iface in $(ls /sys/class/net/ | grep '^wwan'); do
        echo "  oifname \"$iface\" ip6 hoplimit set $ttl" >> "$NFT_FILE"
    done

    cat >> "$NFT_FILE" << EOF
}
EOF
 
    /etc/init.d/firewall restart
 
}

stop_service() {
    local kernel_version
    kernel_version=$(uname -r)

    rm -f "$NFT_FILE" 

    nft delete chain inet fw4 mangle_prerouting_ttl 2>/dev/null
    nft delete chain inet fw4 mangle_postrouting_ttl 2>/dev/null
    nft delete chain inet fw4 mangle_prerouting_hoplimit 2>/dev/null
    nft delete chain inet fw4 mangle_postrouting_hoplimit 2>/dev/null
    /etc/init.d/firewall restart
}

service_triggers() {
    procd_add_reload_trigger "qmodem_ttl"
}

reload_service() {
    stop
    start
}
