#!/bin/sh

mkdir -p /etc/nftables.d
rm -f /etc/nftables.d/*.nft

cat > "/etc/nftables.d/ttl64.nft" << 'EOF'
chain mangle_prerouting_ttl {
  type filter hook prerouting priority 300; policy accept;
  counter ip ttl set 64
}
chain mangle_postrouting_ttl {
  type filter hook postrouting priority 300; policy accept;
  counter ip ttl set 64
}
chain mangle_prerouting_hoplimit {
  type filter hook prerouting priority 300; policy accept;
  counter ip6 hoplimit set 64
  iifname "wwan0" ip6 hoplimit set 64
  iifname "wwan0_1" ip6 hoplimit set 64
}
chain mangle_postrouting_hoplimit {
  type filter hook postrouting priority 300; policy accept;
  counter ip6 hoplimit set 64
  oifname "wwan0" ip6 hoplimit set 64
  oifname "wwan0_1" ip6 hoplimit set 64
}
EOF

uci -q batch << EOF
	delete firewall.qmodem_ttl
	set firewall.qmodem_ttl=include
	set firewall.qmodem_ttl.type=script
	set firewall.qmodem_ttl.path=/etc/nftables.d/ttl64.nft
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
    delete ucitrack.@qmodem_ttl[-1]
	add ucitrack qmodem_ttl
	set ucitrack.@qmodem_ttl[-1].init=qmodem_ttl
	commit ucitrack
EOF

exit 0
