#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

NFT="/usr/sbin/nft"
NFT_DIR="/etc/nftables.d"
NFT_FILE="$NFT_DIR/ttl64.nft"

start_service() {
    config_load 'nftttl'
    config_get enable 'main' 'enable' '0'
    [ "$enable" = "0" ] && return 0

    set_if_ttl
}

set_if_ttl() {
    # Read config
    config_load 'nftttl'
    config_get enabled 'ttl' 'enabled' '0'
    config_get ttl4 'ttl' 'value' '64'
    config_get hl6 'ttl' 'value' '64'  # same as ttl4 if not separate

    [ "$enabled" != "1" ] && return 0

    logger -t modem_ttl "Overwrite IPv4 TTL to $ttl4 and IPv6 Hop Limit to $hl6 (nftables)"

    mkdir -p $NFT_DIR
    [ -f "$NFT_FILE" ] && rm -f "$NFT_FILE"

    cat > $NFT_FILE <<-EOF
chain mangle_prerouting_ttl64 {
    type filter hook prerouting priority 300; policy accept;
    counter
    meta nfproto ipv4 ip ttl set $ttl4
}

chain mangle_postrouting_ttl64 {
    type filter hook postrouting priority 300; policy accept;
    counter
    meta nfproto ipv4 ip ttl set $ttl4
}

chain mangle_prerouting_hoplimit64 {
    type filter hook prerouting priority 300; policy accept;
    counter
    meta nfproto ipv6 ip6 hoplimit set $hl6
}

chain mangle_postrouting_hoplimit64 {
    type filter hook postrouting priority 300; policy accept;
    counter
    meta nfproto ipv6 ip6 hoplimit set $hl6
}
EOF

    $NFT -f $NFT_FILE
    /etc/init.d/firewall reload

    [ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm 2>/dev/null
    [ -d /sys/module/fast_classifier ] && rmmod fast_classifier 2>/dev/null
}

stop_service(){
    logger -t modem_ttl "Remove TTL / HopLimit nft rules"
    local kernel_version=$(uname -r)
    rm -f /etc/firewall.d/nftttl
    rm -f /etc/nftables.d/*.nft
    [ -f /etc/init.d/qca-nss-ecm ] && /etc/init.d/qca-nss-ecm start
    [ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && modprobe shortcut-fe-cm
    [ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && modprobe fast-classifier
    /etc/init.d/firewall restart
}

service_triggers()
{
	procd_add_reload_trigger "nftttl"
}

reload_service()
{
    stop
    start
}
